services:
  festival78-tickets:
    container_name: server
    image: festival78-tickets:latest
    ports:
      - "3000:3000"
    env_file:
      - .env
  nginx:
    container_name: nginx
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
