name: festival78-tickets
services:
  festival78-tickets:
    container_name: server
    image:  ghcr.io/nadadigitalcommittee/festival78-ticket:latest
    volumes:
      - .env:/app/.env
  nginx:
    container_name: nginx
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./ssl:/etc/nginx/ssl