import { Footer } from "@/components/footer";
import { Header } from "@/components/header";
import { SWR } from "@/lib/Swr";
import { SessionProvider } from "@/lib/context";
import { validateSession } from "@/lib/session";
import { Session } from "@/lib/types";
import { ChakraProvider } from "@chakra-ui/react";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ReactNode } from "react";
import "slick-carousel/slick/slick-theme.css";
import "slick-carousel/slick/slick.css";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: ReactNode;
}) {
  const session = await validateSession();
  return (
    <html lang="ja">
      <body className={inter.className + " w-screen"}>
        <Provider session={session}>
          <Header />
          {children}
          <Footer />
        </Provider>
      </body>
    </html>
  );
}

const Provider = ({
  children,
  session,
}: {
  children: ReactNode;
  session?: Session;
}) => {
  return (
    <ChakraProvider>
      <SWR>
        <SessionProvider value={session}>{children}</SessionProvider>
      </SWR>
    </ChakraProvider>
  );
};
