name: Build and Publish Docker

on: 
    pull_request_target:     

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    env:
      IMAGE_NAME: festival78-ticket
      GITHUB_OWNER: nadadigitalcommittee
      MICROCMS_SERVICE_DOMAIN: ${{ secrets.MICROCMS_SERVICE_DOMAIN }}
      MICROCMS_API_KEY: ${{ secrets.MICROCMS_API_KEY }}
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2


      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          platforms: linux/amd64,linux/arm64
          context: .
          push: true
          tags: |
            ghcr.io/${{ env.GITHUB_OWNER }}/${{ env.IMAGE_NAME }}:latest
            ghcr.io/${{ env.GITHUB_OWNER}}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          build-args: |
            MICROCMS_SERVICE_DOMAIN=${{ env.MICROCMS_SERVICE_DOMAIN }}
            MICROCMS_API_KEY=${{ env.MICROCMS_API_KEY }}
